### ISSUE TITLE
tuxinvader/brocade-vtm not available from DockerHub anymore

### ISSUE THREAD

**Issue by juretta** [TuxInvader/Docker-Brocade-vTM#5]
First of all, thanks for putting this together. I found it super useful in the past to quickly run a Brocade VTM locally.

I noticed that tuxinvader/brocade-vtm seems to be gone from DockerHub? 

I get a "This user has not created any repos yet" message when browsing https://hub.docker.com/u/tuxinvader/?

It's easy enough to build the docker image locally so it's not a big deal, just wanted to raise this.

**Comment by TuxInvader** [comment]
Hi Juretta,

Unfortunately I had to remove the container from the hub due to export compliance requirements. An official container (based on this one) will be available from Pulse Secure directly.

Cheers,
Mark
